Repository elementsinteractive/twyn, pull requests merged in 2025-09, with the labels that each got.

#287 fix: Properly annotate `check_dependencies`'s `selector_method` arg
  README.md
  src/twyn/cli.py
  src/twyn/main.py
  tests/conftest.py
  tests/main/test_main.py
Labels: fix

#289 ci: bump checkout action to 5.0.0 in docker-build action
  .github/actions/docker-build/action.yml
Labels: CI

#291 feat: load config from `twyn.toml` if it exists
  README.md
  src/twyn/base/constants.py
  src/twyn/cli.py
  src/twyn/config/config_handler.py
  src/twyn/file_handler/file_handler.py
  src/twyn/main.py
  tests/config/__init__.py
  tests/config/test_config_handler.py
  tests/conftest.py
Labels: feature

#296 ci: preview next version job
  .github/workflows/bump-version.yml
  .github/workflows/docker-build-no-login.yml
  .github/workflows/docker-build.yml
  .github/workflows/preview-bump-version.yml
Labels: CI

#301 ci: add lgtm options
  .github/workflows/lgtm.yml
  pyproject.toml
Labels: CI

#304 chore: Docker Hub badge
  README.md
Labels: ignore-for-release

#311 refactor: rewrite requirements.txt parser and change the way we read files
  pyproject.toml
  src/twyn/base/utils.py
  src/twyn/config/config_handler.py
  src/twyn/dependency_managers/dependency_manager.py
  src/twyn/dependency_parser/lock_parser.py
  src/twyn/dependency_parser/package_lock_json.py
  src/twyn/dependency_parser/parsers/abstract_parser.py
  src/twyn/dependency_parser/parsers/constants.py
  src/twyn/dependency_parser/parsers/lock_parser.py
  src/twyn/dependency_parser/parsers/package_lock_json.py
  src/twyn/dependency_parser/parsers/requirements_txt_parser.py
  src/twyn/file_handler/file_handler.py
  src/twyn/trusted_packages/cache_handler.py
  tests/conftest.py
  tests/dependency_parser/test_dependency_parser.py
  uv.lock
Labels: refactor

#315 ci: adapt to breaking change in lgtm-ai
  .github/workflows/lgtm.yml
Labels: CI

#319 fix: remove wrong formatting in weekly_download.yml
  .github/workflows/weekly_download.yml
Labels: fix

#317 feat: use repo as source of truth
  README.md
  src/twyn/trusted_packages/references/base.py
  src/twyn/trusted_packages/references/top_npm_reference.py
  src/twyn/trusted_packages/references/top_pypi_reference.py
  tests/conftest.py
  tests/main/test_main.py
  tests/trusted_packages/test_references.py
Labels: feature

#322 feat: create `cli` extra group
  .github/workflows/build-test.yml
  .github/workflows/security.yml
  .github/workflows/test.yml
  README.md
  dependencies/scripts/download_packages.py
  justfile
  pyproject.toml
  src/twyn/base/exceptions.py
  src/twyn/cli.py
  src/twyn/main.py
  tests/main/conftest.py
  tests/main/test_main.py
  uv.lock
Labels: feature, v5.0.0

#332 feat: recursively look for lock files
  .gitignore
  README.md
  src/twyn/base/constants.py
  src/twyn/cli.py
  src/twyn/config/config_handler.py
  src/twyn/dependency_parser/dependency_selector.py
  src/twyn/main.py
  tests/config/test_config_handler.py
  tests/conftest.py
  tests/dependency_parser/test_dependency_selector.py
  tests/main/test_cli.py
  tests/main/test_main.py
Labels: feature

#335 feat: support multiple dependency files in config and cli
  src/twyn/cli.py
  src/twyn/config/config_handler.py
  src/twyn/dependency_parser/dependency_selector.py
  src/twyn/main.py
  tests/config/test_config_handler.py
  tests/conftest.py
  tests/dependency_parser/test_dependency_selector.py
  tests/main/conftest.py
  tests/main/test_cli.py
  tests/main/test_main.py
Labels: feature

#345 feat: allow to set ecosystem sources via the cli
  src/twyn/cli.py
  src/twyn/config/config_handler.py
  src/twyn/main.py
  tests/main/test_cli.py
  tests/main/test_main.py
Labels: feature
